source 'https://rubygems.org'

gem 'rails', '3.2.18'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

gem 'devise',      '~> 3.1'
gem 'simple_form', '~> 2.0'
gem 'paperclip'

# SEO pack
gem 'meta-tags', :require => 'meta_tags'

# exception handle
gem 'exception_notification'

# pixelforce template
gem 'pixelforce_cms', '~> 0.9.9.5'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  #HTML5
  gem 'compass-rails', '~> 1.1.7'
  gem 'compass-h5bp', '~> 0.1.2'
  gem 'uglifier', '>= 1.0.3'

  #Bootstrap
  gem "therubyracer"
  gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
  gem 'bootstrap-sass', '~> 3.0.3.0'
  
  gem 'jquery-ui-rails'         
  gem 'fancybox2-rails', '~> 0.2.4'                       
end

group :development, :test do
  gem 'quiet_assets'
  gem 'rspec'
  gem 'rspec-rails',       '~> 2.13'
  # Deploy with Capistrano
  gem 'capistrano'
  gem 'rvm-capistrano'
  gem "capistrano-db-tasks", require: false, github: 'gkopylov/capistrano-db-tasks', ref: 'f3949cd'
  gem 'factory_girl_rails'
  gem 'thin'
end

gem "font-awesome-rails"
gem 'sass'
gem 'html5-rails'
gem 'jquery-rails'

gem 'haml', '~> 4.0.0'
gem 'haml-rails', '~> 0.4'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
